// LOCALHOST 
### 
GET http://localhost:8080/events
### 
GET http://localhost:8080/users
### 
POST http://localhost:8080/contacts/
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "johndoe@gmail.com",
  "favoriteColor": "Yellow",
  "birthday": "May 30"
}